### ISSUE TITLE
Input type date or datetime-local for filtering

### ISSUE THREAD

**Issue by philipborg** [ErlendLandro/WasteTrader#14]
Currently Oldest and Youngest parameters are commented out due to html issues. I need a Int64 from input type date or datetime-local. Should I parse it on the client in JS or in code-behind?

Also, fallback is needed for browsers not supporting date or datetime-local input types. (Concerned browsers are Firefox and IE.) Found [related stackoverflow question](https://stackoverflow.com/questions/30503195/html-5-input-type-date-not-working-in-firefox).

**Comment by ErlendLandro** [comment]
> Should I parse it on the client in JS or in code-behind?

It's best to parse in the code-behind.

> Also, fallback is needed for browsers not supporting date or datetime-local input types. (Concerned browsers are Firefox and IE.) 

I would just give a notification if the format is wrong. Let this be checked in the code-behind on input and sent to the client for the user to see.
