### ISSUE TITLE
LongitudeDD and LatitudeDD

### ISSUE THREAD

**Issue by philipborg** [ErlendLandro/WasteTrader#15]
We currently have no way to set Long/lat-itude in filter. I think we should use [Googles Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro#geocoding). The problem is it is only free for 2 500 requests per day. Alternatively [Nominatim](http://wiki.openstreetmap.org/wiki/Nominatim#Search) which uses OpenStreetMap and allows 1 Request per second, however autocomplete is forbidden and caching is demanded. Technically one can host their own Nominatim server without restrictions which would be ideal but at the same time overkill. Both responds in either XML or JSON. Either solution needs a bit of JS unless we do it in code-behind, but I think that this should be on the client to decrease unnecessary server load with the server acting as a proxy.
Opinion?

**Comment by ErlendLandro** [comment]
Googles Geocoding API is no problem, 2500 requests will not be a limitation for some time and it's quite easy to increase by paying. I think it's the best solution.
